apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-service
  name: java-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: java-service
          image: java-service:edge
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
  labels:
    app: java-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-service
  sessionAffinity: None
  type: ClusterIP

